language: php

php:
  - 5.4
  - 5.5

script:
  - vendor/bin/doctrine orm:schema-tool:create
  - vendor/bin/codecept build
  - vendor/bin/codecept run unit
before_script:
  - mysql -e 'create database mabes;'
  - mv app/Config/Config.php.travis app/Config/Config.php
  - wget http://getcomposer.org/composer.phar
  - php composer.phar self-update
  - php composer.phar install